config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :articles
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  get :favorites, to: 'favorites#index'
  post   "favorites/:article_id/create"  => "favorites#create"
  delete "favorites/:article_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :logs, only: [:create, :destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :article_id, presence: true
  validates :variety, presence: true
  validates :from_user_id, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :logged_in_user

  def index
    @notifications = current_user.notifications
    current_user.update_attribute(:notification, false)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% user = User.find(notification.from_user_id) %>
<% article = Article.find(notification.article_id) %>
<li id="notification-<%= notification.id %>">
  <div>
    <% if notification.variety == 1 %>
      <p><%= notification.created_at.strftime("%Y/%m/%d(%a) %H:%M") %></p>
      <p class="notification-message">あなたの投稿が<%= link_to user.name, user_path(user) %>さんにお気に入り登録されました。</p>
    <% elsif notification.variety == 2 %>
      <p><%= notification.created_at.strftime("%Y/%m/%d(%a) %H:%M") %></p>
      <p class="notification-message">あなたの投稿に<%= link_to user.name, user_path(user) %>さんがコメントしました。
      「<%= notification.content %>」</p>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= link_to((image_tag article.images.first.src.url), article_path(article), class: 'article-picture') %>
    </div>
    <div class="col-md-7">
      <p><%= link_to article.name, article_path(article) %></p>
      <p><%= article.description %></p>
    </div>
  </div>
</li>

app/views/notifications/index.html.erb
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3>通知一覧</h3>
    </div>
  </div>
  <% if @notifications.present? %>
    <ol class="notifications">
      <%= render @notifications %>
    </ol>
  <% end %>
</div>