config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :articles
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  get :favorites, to: 'favorites#index'
  post   "favorites/:article_id/create"  => "favorites#create"
  delete "favorites/:article_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :logs, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2020 Your Name All Rights Reserved.</small>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="top-header">
  <nav class="gnav">
    <ul class="gnav-list fadeIn fade-in">
      <li class="gnav-item gnav-main"><%= link_to 'HOME', root_url %></li>
      <li class="gnav-item gnav-main"><%= link_to 'ABOUT', about_path %></li>
      <li class="gnav-item gnav-main"><%= link_to 'TERMS', use_of_terms_path %></li>
      <% if logged_in? %>
        <% if current_user.notification == true %>
          <li class="new_notification header-link">
        <% else %>
          <li class="no_notification header-link">
        <% end %>
        <%= link_to notifications_path do %><span>NOTIFICATION</span><% end %>
        </li>
        <li><%= link_to 'FAVORITE', favorites_path %></li>
        <li><%= link_to 'USERLIST', users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            ACCOUNT <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'PROFILE', current_user %></li>
            <li class="divider"></li>
            <li><%= link_to 'LOGOUT', logout_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li class="gnav-item gnav-main"><%= link_to 'SIGN UP', signup_path %></li>
        <li class="gnav-item gnav-main"><%= link_to 'LOGIN', login_path %></li>
      <% end %>
      <li class="gnav-item gnav-main"><a href="access/index.html">ACCESS</a></li>
      <li class="gnav-item gnav-main"><a href="contact/index.html">CONTACT</a></li>
      <li class="gnav-item gnav-sns"><a href="" target="_blank"><i class="fab fa-instagram faa-wrench animated-hover"></i></a></li>
      <li class="gnav-item gnav-sns"><a href="" target="_blank"><i class="fab fa-twitter-square faa-wrench animated-hover"></i></a></li>
      <li class="gnav-item gnav-sns"><a href="" target="_blank"><i class="fab fa-facebook-square faa-wrench animated-hover"></i></a></li>
    </ul>
  </nav>
  <button class="btn-trigger">
    <span></span>
    <span></span>
    <span></span>
  </button>
</header>

app/views/layouts/_loading.html.erb
<div class="mainvisual" id="mainvisual">	
  <div class="key-img"></div>
  <div class="mainvisual-left">
    <h2>CAFE LOG</h2>
    <div class="scrolldown">
      <div class="arrowWrap">
        <div class="arrowInner">
          <div class="arrow"></div>
          <p>Scroll</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://kit.fontawesome.com/84eeecacff.js" crossorigin="anonymous"></script>

app/views/layouts/_search.html.erb
<div class="row">
  <%= search_form_for @q do |f| %>
    <div class="col-md-10">
      <div class='form-group'>
        <%= f.search_field :name_cont, placeholder: "投稿名で検索", class: 'form-control font-awesome' %>
      </div>
    </div>
    <div class="col-md-2">
      <div class='form-group'>
        <%= f.submit nil, class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="page">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>